name: E2E Test
on:
  pull_request:
    paths:
      - .github/workflows/e2e-test.yml
      - src/**
      - WebExample/**
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/e2e-test.yml
      - src/**
      - WebExample/**

jobs:
  e2e_test:
    if: github.repository == 'Expensify/react-native-live-markdown'
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./WebExample

    container:
      image: mcr.microsoft.com/playwright:v1.43.1-jammy
    concurrency:
      group: e2e-test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install node_modules
        run: yarn install --immutable

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: Run playwright tests
        run: yarn test
        env:
          HOME: /root
